name: 'Protect integration branch'

on:
  workflow_dispatch:
    inputs:
      actionName:
        type: choice
        description: 'Lock or Unlock the branch'
        required: true
        default: 'lock'
        options:
          - 'lock'
          - 'unlock'

jobs:
  lock-the-branch-info:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      #   with:
      #     sparse-checkout: |
      #       .github
      #       src
      # - name: 'Js lock'
      #   run:
      - name: 'Lock / unlock branch'
        run: |
          curl -L -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" -d '{"lock_branch":true, "enforce_admins":true,"required_pull_request_reviews":null,"required_status_checks":null,"restrictions": null}' https://api.github.com/repos/dil-ntoth/actions_test/branches/$GITHUB_REF_NAME/protection
        env:
          ACTION_NAME: ${{ inputs.actionName }}

# if [ "$ACTION_NAME" == "unlock" ]; then curl -L -X DELETE -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/dil-ntoth/actions_test/branches/$GITHUB_REF_NAME/protection ; fi
