name: 'Protect integration branch'

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch name'
        required: true
        default: 'integration'
        type: choice
        options:
        - integration
      actionName:
        type: choice
        description: 'Lock or Unlock the branch'
        required: true
        default: 'lock'
        options:
          - 'lock'
          - 'unlock'

jobs:
  lock-the-branch-info:
    runs-on: ubuntu-latest
    steps:
      - name: 'Lock / unlock branch'
        run: |
          echo "Initiator: $GITHUB_ACTOR"
          echo "URL: https://api.github.com/repos/dil-ntoth/actions_test/branches/$GITHUB_REF_NAME/protection"
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -d '{"lock_branch":true, "enforce_admins":true,"required_pull_request_reviews":null,"required_status_checks":null,"restrictions": null}'\
          -X PUT https://api.github.com/repos/dil-ntoth/actions_test/branches/main/protection

          # if [ "$ACTION_NAME" == "lock" ]; then curl -L \
          # -H "Accept: application/vnd.github+json" \
          # -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
          # -H "X-GitHub-Api-Version: 2022-11-28" \
          # -d '{"lock_branch":true, "enforce_admins":true,"required_pull_request_reviews":null,"required_status_checks":null,"restrictions": null}'\
          # -X PUT https://api.github.com/repos/dil-ntoth/actions_test/branches/main/protection \
          # ; fi
          # if [ "$ACTION_NAME" == "unlock" ]; then curl -L \
          # -X DELETE \
          # -H "Accept: application/vnd.github+json" \
          # -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
          # -H "X-GitHub-Api-Version: 2022-11-28" \
          # https://api.github.com/repos/dil-ntoth/actions_test/branches/$GITHUB_REF_NAME/protection \
          # ; fi
        env:
          BRANCH_NAME: ${{ inputs.branchName }}
          ACTION_NAME: ${{ inputs.actionName }}

