name: 'Protect integration branch'

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch name'
        required: true
        default: 'integration'
        type: choice
        options:
        - integration
      actionName:
        type: choice
        description: 'Lock or Unlock the branch'
        required: true
        default: 'lock'
        options:
          - 'lock'
          - 'unlock'

jobs:
  lock-the-branch-info:
    runs-on: ubuntu-latest
    steps:
      # - name: 'Lock/unlock the branch'
      #   run: |
      #     echo "Branch name: $BRANCH_NAME"
      #     echo "Action name: $ACTION_NAME"
      #     curl "https://dummyjson.com/products/1?b=$BRANCH_NAME"
      #   env:
      #     BRANCH_NAME: ${{ inputs.branchName }}
      #     ACTION_NAME: ${{ inputs.actionName }}
      - name: 'lock'
        run: >
          curl -L \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/dil-ntoth/actions_test/branches/$BRANCH_NAME/protection \
          -d '{"lock_branch":true, "enforce_admins":true,"required_pull_request_reviews":null,"required_status_checks":null,"restrictions":{users: [], teams: []}}'
        env:
          BRANCH_NAME: ${{ inputs.branchName }}
          ACTION_NAME: ${{ inputs.actionName }}
      # - name: 'unlock'
      #   run: >
      #     curl -L \
      #     -X DELETE \
      #     -H "Accept: application/vnd.github+json" \
      #     -H "Authorization: Bearer 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"\
      #     -H "X-GitHub-Api-Version: 2022-11-28" \
      #     https://api.github.com/repos/dil-ntoth/actions_test/branches/$BRANCH_NAME/protection
      #   env:
      #     BRANCH_NAME: ${{ inputs.branchName }}
      #     ACTION_NAME: ${{ inputs.actionName }}


# -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
