name: 'Protect integration branch'

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch name'
        required: true
        default: 'integration'
        type: choice
        options:
        - integration
      actionName:
        type: choice
        description: 'Lock or Unlock the branch'
        required: true
        default: 'lock'
        options:
          - 'lock'
          - 'unlock'

jobs:
  lock-the-branch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Branch name: $BRANCH_NAME"
          echo "Action name: $ACTION_NAME"
          curl "https://dummyjson.com/products/1?b=$BRANCH_NAME"
        env:
          BRANCH_NAME: ${{ inputs.branchName }}
          ACTION_NAME: ${{ inputs.actionName }}
          