name: 'Protect integration branch'

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch name'
        required: true
        default: 'integration'
        type: choice
        options:
        - integration
      actionName:
        type: choice
        description: 'Lock or Unlock the branch'
        required: true
        default: 'lock'
        options:
          - 'lock'
          - 'unlock'

jobs:
  lock-the-branch-info:
    runs-on: ubuntu-latest
    steps:
      # - name: 'Lock/unlock the branch'
      #   run: |
      #     echo "Branch name: $BRANCH_NAME"
      #     echo "Action name: $ACTION_NAME"
      #     curl "https://dummyjson.com/products/1?b=$BRANCH_NAME"
      #   env:
      #     BRANCH_NAME: ${{ inputs.branchName }}
      #     ACTION_NAME: ${{ inputs.actionName }}
      - name: 'Lock'
        run: >
          curl -L -X PUT 
          -H "Accept: application/vnd.github+json" 
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
          -H "X-GitHub-Api-Version: 2022-11-28" 
          https://api.github.com/repos/dil-ntoth/actions_test/branches/integration/protection 
          -d '{"required_status_checks":{"strict":true,"contexts":["continuous-integration/travis-ci"]},"enforce_admins":true,"required_pull_request_reviews":{"dismissal_restrictions":{"users":["octocat"],"teams":["justice-league"]},"dismiss_stale_reviews":true,"require_code_owner_reviews":true,"required_approving_review_count":2,"require_last_push_approval":true,"bypass_pull_request_allowances":{"users":["octocat"],"teams":["justice-league"]}},"restrictions":{"users":["octocat"],"teams":["justice-league"],"apps":["super-ci"]},"required_linear_history":true,"allow_force_pushes":true,"allow_deletions":true,"block_creations":true,"required_conversation_resolution":true,"lock_branch":true,"allow_fork_syncing":true}'  
        env:
          BRANCH_NAME: ${{ inputs.branchName }}
          ACTION_NAME: ${{ inputs.actionName }}  