name: 'Protect integration branch'

on:
  workflow_dispatch:
    inputs:
      actionName:
        type: choice
        description: 'Lock or Unlock the branch'
        required: true
        default: 'lock'
        options:
          - 'lock'
          - 'unlock'

jobs:
  lock-the-branch-info:
    runs-on: ubuntu-latest
    steps:
      - name: 'Lock branch'
        if: ${{ env.ACTION_NAME == 'lock' }}
        run: |
          CODE=`curl -L \
            --request PUT \
            --header 'authorization: Bearer $SECRET_PAT' \
            --header 'content-type: application/vnd.github+json' \
            --header 'X-GitHub-Api-Version: 2022-11-28' \
            --url 'https://api.github.com/repos/dil-ntoth/actions_test/branches/$GITHUB_REF_NAME/protection' \
            --data '{"lock_branch":true, "enforce_admins":true,"required_pull_request_reviews":null,"required_status_checks":null,"restrictions": null}'`

          if [ $CODE!="200" ]
          then
            echo $CODE
            exit 1
          else
            echo $CODE
            echo "SUCCESS"
          fi
        env:
          ACTION_NAME: ${{ inputs.actionName }}
          SECRET_PAT: ${{ secrets.PAT }}

      - name: 'Unlock branch'
        if: ${{ env.ACTION_NAME == 'unlock' }}
        run: |
          curl -L -X DELETE -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $SECRET_PAT" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/dil-ntoth/actions_test/branches/$GITHUB_REF_NAME/protection
        shell: bash
        env:
          ACTION_NAME: ${{ inputs.actionName }}
          SECRET_PAT: ${{ secrets.PAT }}


# curl -L -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" -d '{"lock_branch":true, "enforce_admins":true,"required_pull_request_reviews":null,"required_status_checks":null,"restrictions": null}' https://api.github.com/repos/dil-ntoth/actions_test/branches/main/protection
# if [ "$ACTION_NAME" == "unlock" ]; then curl -L -X DELETE -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/dil-ntoth/actions_test/branches/$GITHUB_REF_NAME/protection ; fi


